/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    topic: Topic;
    subTopic: SubTopic;
    syllabus: Syllabus;
    syllabusSubTopic: SyllabusSubTopic;
    question: Question;
    studySession: StudySession;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    topic: TopicSelect<false> | TopicSelect<true>;
    subTopic: SubTopicSelect<false> | SubTopicSelect<true>;
    syllabus: SyllabusSelect<false> | SyllabusSelect<true>;
    syllabusSubTopic: SyllabusSubTopicSelect<false> | SyllabusSubTopicSelect<true>;
    question: QuestionSelect<false> | QuestionSelect<true>;
    studySession: StudySessionSelect<false> | StudySessionSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Optional frontend/admin roles. Users may have zero, one, or multiple roles.
   */
  roles?: ('admin' | 'student')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Topics are the broadest curriculum groupings used to organise subtopics.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topic".
 */
export interface Topic {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Subtopics are the curriculum tags applied to questions and worked solutions. Each belongs to one parent topic.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subTopic".
 */
export interface SubTopic {
  id: string;
  name: string;
  topic: string | Topic;
  updatedAt: string;
  createdAt: string;
}
/**
 * Syllabuses define coverage over the existing topic and subtopic taxonomy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syllabus".
 */
export interface Syllabus {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Matrix-first coverage mapping between syllabuses and subtopics.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syllabusSubTopic".
 */
export interface SyllabusSubTopic {
  id: string;
  syllabus: string | Syllabus;
  subTopic: string | SubTopic;
  status: 'included' | 'assumedKnowledge';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "question".
 */
export interface Question {
  id: string;
  /**
   * Use this for the full prompt on single-part questions, or shared context that sits above all parts on multipart questions.
   */
  prompt?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Single-part questions still use one part row. Add more rows only when the question genuinely has multiple parts.
   */
  parts: {
    /**
     * Only shown for multipart questions. Keep any single-part prompt content at the top level instead.
     */
    prompt?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Choose how the learner responds to this part.
     */
    response: {
      type: 'multipleChoice' | 'shortText' | 'selfReport';
      multipleChoice?: {
        choices?:
          | {
              text: string;
              isCorrect: boolean;
              id?: string | null;
            }[]
          | null;
        shuffle: boolean;
      };
      shortText?: {
        acceptedAnswers?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
      };
      selfReport?: {};
    };
    /**
     * Optional authored worked solutions shown after submission. They remain hidden until review is requested.
     */
    workedSolutions?:
      | {
          prompt: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          /**
           * Optional supporting subtopics used for filtering or analytics. These are not shown directly to students.
           */
          subTopics?: (string | SubTopic)[] | null;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  /**
   * Optional question-level subtopics. Learner-facing taxonomy is derived from these tags only.
   */
  subTopics?: (string | SubTopic)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Persisted student study sessions with locked question versions and answers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studySession".
 */
export interface StudySession {
  id: string;
  user: string | User;
  state?: ('notStarted' | 'started' | 'finished') | null;
  begunAt?: string | null;
  endedAt?: string | null;
  questions: {
    question: string | Question;
    questionVersionId?: string | null;
    status: 'notStarted' | 'skipped' | 'answered';
    flagged: boolean;
    answeredAt?: string | null;
    skippedAt?: string | null;
    answers?:
      | {
          partId: string;
          type: 'unanswered' | 'multipleChoice' | 'shortText' | 'selfReport';
          multipleChoice?: {
            choiceId?: string | null;
          };
          shortText?: {
            answer?: string | null;
          };
          selfReport?: {
            answer?: boolean | null;
          };
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'topic';
        value: string | Topic;
      } | null)
    | ({
        relationTo: 'subTopic';
        value: string | SubTopic;
      } | null)
    | ({
        relationTo: 'syllabus';
        value: string | Syllabus;
      } | null)
    | ({
        relationTo: 'syllabusSubTopic';
        value: string | SyllabusSubTopic;
      } | null)
    | ({
        relationTo: 'question';
        value: string | Question;
      } | null)
    | ({
        relationTo: 'studySession';
        value: string | StudySession;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topic_select".
 */
export interface TopicSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subTopic_select".
 */
export interface SubTopicSelect<T extends boolean = true> {
  name?: T;
  topic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syllabus_select".
 */
export interface SyllabusSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "syllabusSubTopic_select".
 */
export interface SyllabusSubTopicSelect<T extends boolean = true> {
  syllabus?: T;
  subTopic?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "question_select".
 */
export interface QuestionSelect<T extends boolean = true> {
  prompt?: T;
  parts?:
    | T
    | {
        prompt?: T;
        response?:
          | T
          | {
              type?: T;
              multipleChoice?:
                | T
                | {
                    choices?:
                      | T
                      | {
                          text?: T;
                          isCorrect?: T;
                          id?: T;
                        };
                    shuffle?: T;
                  };
              shortText?:
                | T
                | {
                    acceptedAnswers?:
                      | T
                      | {
                          value?: T;
                          id?: T;
                        };
                  };
              selfReport?: T | {};
            };
        workedSolutions?:
          | T
          | {
              prompt?: T;
              subTopics?: T;
              id?: T;
            };
        id?: T;
      };
  subTopics?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studySession_select".
 */
export interface StudySessionSelect<T extends boolean = true> {
  user?: T;
  state?: T;
  begunAt?: T;
  endedAt?: T;
  questions?:
    | T
    | {
        question?: T;
        questionVersionId?: T;
        status?: T;
        flagged?: T;
        answeredAt?: T;
        skippedAt?: T;
        answers?:
          | T
          | {
              partId?: T;
              type?: T;
              multipleChoice?:
                | T
                | {
                    choiceId?: T;
                  };
              shortText?:
                | T
                | {
                    answer?: T;
                  };
              selfReport?:
                | T
                | {
                    answer?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}